name: manage-azure-policy-0d6345eb
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Assign_Built-In_User-Assigned_Managed_Identity_to_Virtual_Machines_d367bd60-64ca-4364-98ea-276775bddd94/**'
#      - .github/workflows/manage-azure-policy-0d6345eb.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_0d6345eb}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Assign_Built-In_User-Assigned_Managed_Identity_to_Virtual_Machines_d367bd60-64ca-4364-98ea-276775bddd94/**
